# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen+github@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_drag_n_drop_path
project_short_description: Jupyterlab extension to allow file or folder to be dragged-and-dropped
    to terminal. And to turn into a path. And if the terminal is a python file or
    not a terminal but python notebook - it would be turned either into path again
    (default) or to Pathlib expression (depending on the config in the settings)
python_name: jupyterlab_drag_n_drop_path
repository: ''
test: true

